# Generated by Django 5.0.2 on 2024-03-07 18:18

import app.src.shared.enums
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='C_1_identification_of_the_case_safety_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_1_1_senders_safety_report_unique_identifier', models.CharField(max_length=100, null=True, unique=True)),
                ('c_1_2_date_of_creation', models.CharField(max_length=24, null=True)),
                ('c_1_3_type_of_report', models.IntegerField(null=True)),
                ('c_1_4_date_report_was_first_received_from_source', models.CharField(max_length=24, null=True)),
                ('c_1_5_date_of_most_recent_information_for_this_report', models.CharField(max_length=24, null=True)),
                ('c_1_6_1_are_additional_documents_available', models.BooleanField(null=True)),
                ('c_1_7_does_this_case_fulfill_the_local_criteria_for_an_e', models.BooleanField(null=True)),
                ('nf_c_1_7_does_this_case_fulfill_the_local_criteria_for_an_e', models.CharField(max_length=4, null=True)),
                ('c_1_8_1_worldwide_unique_case_identification_number', models.CharField(max_length=100, null=True, unique=True)),
                ('c_1_8_2_first_sender_of_this_case', models.IntegerField(null=True)),
                ('c_1_9_1_other_case_identifiers_in_previous_transmissions', models.BooleanField(null=True)),
                ('nf_c_1_9_1_other_case_identifiers_in_previous_transmissions', models.CharField(max_length=4, null=True)),
                ('c_1_11_1_report_nullification_or_amendment', models.IntegerField(null=True)),
                ('c_1_11_2_reason_for_nullification_or_amendment', models.CharField(max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ICSR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='C_1_9_1_r_other_case_identifiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_1_9_1_r_1_source_of_the_case_identifier', models.CharField(max_length=100, null=True)),
                ('c_1_9_1_r_2_case_identifier', models.CharField(max_length=100, null=True)),
                ('c_1_identification_of_the_case_safety_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_1_9_1_r_other_case_identifiers', to='app.c_1_identification_of_the_case_safety_report')),
            ],
        ),
        migrations.CreateModel(
            name='C_1_6_1_r_documents_held_by_sender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_1_6_1_r_1_documents_held_by_sender', models.CharField(max_length=2000, null=True)),
                ('c_1_identification_of_the_case_safety_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_1_6_1_r_documents_held_by_sender', to='app.c_1_identification_of_the_case_safety_report')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='C_1_10_r_identification_number_of_the_report_which_is_li',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_1_10_r_identification_number_of_the_report_which_is_li', models.CharField(max_length=100, null=True)),
                ('c_1_identification_of_the_case_safety_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_1_10_r_identification_number_of_the_report_which_is_li', to='app.c_1_identification_of_the_case_safety_report')),
            ],
        ),
        migrations.AddField(
            model_name='c_1_identification_of_the_case_safety_report',
            name='icsr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='c_1_identification_of_the_case_safety_report', to='app.icsr'),
        ),
        migrations.AddConstraint(
            model_name='c_1_9_1_r_other_case_identifiers',
            constraint=models.UniqueConstraint(fields=('c_1_identification_of_the_case_safety_report', 'c_1_9_1_r_2_case_identifier'), name='unqtgr__c_1_identification_of_the__c_1_9_1_r_2_case_identifi'),
        ),
        migrations.AddConstraint(
            model_name='c_1_10_r_identification_number_of_the_report_which_is_li',
            constraint=models.UniqueConstraint(fields=('c_1_identification_of_the_case_safety_report', 'c_1_10_r_identification_number_of_the_report_which_is_li'), name='unqtgr__c_1_identification_of_the__c_1_10_r_identification_n'),
        ),
        migrations.AddConstraint(
            model_name='c_1_identification_of_the_case_safety_report',
            constraint=models.CheckConstraint(check=models.Q(('c_1_3_type_of_report__in', app.src.shared.enums.C_1_3_type_report)), name='choics__c_1_3_type_of_report'),
        ),
        migrations.AddConstraint(
            model_name='c_1_identification_of_the_case_safety_report',
            constraint=models.CheckConstraint(check=models.Q(('nf_c_1_7_does_this_case_fulfill_the_local_criteria_for_an_e__in', [app.src.shared.enums.NullFlavor['NI']])), name='choics__nf_c_1_7_does_this_case_fulfill_the_local_criteria_fo'),
        ),
        migrations.AddConstraint(
            model_name='c_1_identification_of_the_case_safety_report',
            constraint=models.CheckConstraint(check=models.Q(('c_1_7_does_this_case_fulfill_the_local_criteria_for_an_e__isnull', True), ('nf_c_1_7_does_this_case_fulfill_the_local_criteria_for_an_e__isnull', True), _connector='OR'), name='anynul__c_1_7_does_this_case_fulf__nf_c_1_7_does_this_case_f'),
        ),
        migrations.AddConstraint(
            model_name='c_1_identification_of_the_case_safety_report',
            constraint=models.CheckConstraint(check=models.Q(('c_1_8_2_first_sender_of_this_case__in', app.src.shared.enums.C_1_8_2_first_sender)), name='choics__c_1_8_2_first_sender_of_this_case'),
        ),
        migrations.AddConstraint(
            model_name='c_1_identification_of_the_case_safety_report',
            constraint=models.CheckConstraint(check=models.Q(('c_1_9_1_other_case_identifiers_in_previous_transmissions__in', [True])), name='choics__c_1_9_1_other_case_identifiers_in_previous_transmissi'),
        ),
        migrations.AddConstraint(
            model_name='c_1_identification_of_the_case_safety_report',
            constraint=models.CheckConstraint(check=models.Q(('nf_c_1_9_1_other_case_identifiers_in_previous_transmissions__in', [app.src.shared.enums.NullFlavor['NI']])), name='choics__nf_c_1_9_1_other_case_identifiers_in_previous_transmi'),
        ),
        migrations.AddConstraint(
            model_name='c_1_identification_of_the_case_safety_report',
            constraint=models.CheckConstraint(check=models.Q(('c_1_9_1_other_case_identifiers_in_previous_transmissions__isnull', True), ('nf_c_1_9_1_other_case_identifiers_in_previous_transmissions__isnull', True), _connector='OR'), name='anynul__c_1_9_1_other_case_identi__nf_c_1_9_1_other_case_ide'),
        ),
        migrations.AddConstraint(
            model_name='c_1_identification_of_the_case_safety_report',
            constraint=models.CheckConstraint(check=models.Q(('c_1_11_1_report_nullification_or_amendment__in', app.src.shared.enums.C_1_11_1_report_nullification_amendment)), name='choics__c_1_11_1_report_nullification_or_amendment'),
        ),
    ]
