# Generated by Django 5.0.2 on 2024-03-13 11:59

import app.src.enums
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='c_1_6_1_r_documents_held_by_sender',
            name='c_1_identification_of_the_case_safety_report',
        ),
        migrations.RemoveField(
            model_name='c_1_9_1_r_other_case_identifiers',
            name='c_1_identification_of_the_case_safety_report',
        ),
        migrations.RemoveField(
            model_name='c_1_identification_of_the_case_safety_report',
            name='icsr',
        ),
        migrations.CreateModel(
            name='C_1_identification_case_safety_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_1_1_sender_safety_report_unique_id', models.CharField(max_length=100, null=True, unique=True)),
                ('c_1_2_date_creation', models.CharField(max_length=24, null=True)),
                ('c_1_3_type_report', models.IntegerField(null=True)),
                ('c_1_4_date_report_first_received_source', models.CharField(max_length=24, null=True)),
                ('c_1_5_date_most_recent_information', models.CharField(max_length=24, null=True)),
                ('c_1_6_1_additional_documents_available', models.BooleanField(null=True)),
                ('c_1_7_fulfil_local_criteria_expedited_report', models.BooleanField(null=True)),
                ('nf_c_1_7_fulfil_local_criteria_expedited_report', models.CharField(max_length=4, null=True)),
                ('c_1_8_1_worldwide_unique_case_identification_number', models.CharField(max_length=100, null=True, unique=True)),
                ('c_1_8_2_first_sender', models.IntegerField(null=True)),
                ('c_1_9_1_other_case_ids_previous_transmissions', models.BooleanField(null=True)),
                ('nf_c_1_9_1_other_case_ids_previous_transmissions', models.CharField(max_length=4, null=True)),
                ('c_1_11_1_report_nullification_amendment', models.IntegerField(null=True)),
                ('c_1_11_2_reason_nullification_amendment', models.CharField(max_length=2000, null=True)),
                ('icsr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='c_1_identification_case_safety_report', to='app.icsr')),
            ],
        ),
        migrations.CreateModel(
            name='C_1_9_1_r_source_case_id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_1_9_1_r_1_source_case_id', models.CharField(max_length=100, null=True)),
                ('c_1_9_1_r_2_case_id', models.CharField(max_length=100, null=True)),
                ('c_1_identification_case_safety_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_1_9_1_r_source_case_id', to='app.c_1_identification_case_safety_report')),
            ],
        ),
        migrations.CreateModel(
            name='C_1_6_1_r_documents_held_sender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_1_6_1_r_1_documents_held_sender', models.CharField(max_length=2000, null=True)),
                ('c_1_identification_case_safety_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_1_6_1_r_documents_held_sender', to='app.c_1_identification_case_safety_report')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='C_1_10_r_identification_number_report_linked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_1_10_r_identification_number_report_linked', models.CharField(max_length=100, null=True)),
                ('c_1_identification_case_safety_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_1_10_r_identification_number_report_linked', to='app.c_1_identification_case_safety_report')),
            ],
        ),
        migrations.DeleteModel(
            name='C_1_10_r_identification_number_of_the_report_which_is_li',
        ),
        migrations.DeleteModel(
            name='C_1_6_1_r_documents_held_by_sender',
        ),
        migrations.DeleteModel(
            name='C_1_9_1_r_other_case_identifiers',
        ),
        migrations.DeleteModel(
            name='C_1_identification_of_the_case_safety_report',
        ),
        migrations.AddConstraint(
            model_name='c_1_identification_case_safety_report',
            constraint=models.CheckConstraint(check=models.Q(('c_1_3_type_report__in', app.src.enums.C_1_3_type_report)), name='choics__c_1_3_type_report'),
        ),
        migrations.AddConstraint(
            model_name='c_1_identification_case_safety_report',
            constraint=models.CheckConstraint(check=models.Q(('nf_c_1_7_fulfil_local_criteria_expedited_report__in', [app.src.enums.NullFlavor['NI']])), name='choics__nf_c_1_7_fulfil_local_criteria_expedited_report'),
        ),
        migrations.AddConstraint(
            model_name='c_1_identification_case_safety_report',
            constraint=models.CheckConstraint(check=models.Q(('c_1_7_fulfil_local_criteria_expedited_report__isnull', True), ('nf_c_1_7_fulfil_local_criteria_expedited_report__isnull', True), _connector='OR'), name='anynul__c_1_7_fulfil_local_criter__nf_c_1_7_fulfil_local_cri'),
        ),
        migrations.AddConstraint(
            model_name='c_1_identification_case_safety_report',
            constraint=models.CheckConstraint(check=models.Q(('c_1_8_2_first_sender__in', app.src.enums.C_1_8_2_first_sender)), name='choics__c_1_8_2_first_sender'),
        ),
        migrations.AddConstraint(
            model_name='c_1_identification_case_safety_report',
            constraint=models.CheckConstraint(check=models.Q(('c_1_9_1_other_case_ids_previous_transmissions__in', [True])), name='choics__c_1_9_1_other_case_ids_previous_transmissions'),
        ),
        migrations.AddConstraint(
            model_name='c_1_identification_case_safety_report',
            constraint=models.CheckConstraint(check=models.Q(('nf_c_1_9_1_other_case_ids_previous_transmissions__in', [app.src.enums.NullFlavor['NI']])), name='choics__nf_c_1_9_1_other_case_ids_previous_transmissions'),
        ),
        migrations.AddConstraint(
            model_name='c_1_identification_case_safety_report',
            constraint=models.CheckConstraint(check=models.Q(('c_1_9_1_other_case_ids_previous_transmissions__isnull', True), ('nf_c_1_9_1_other_case_ids_previous_transmissions__isnull', True), _connector='OR'), name='anynul__c_1_9_1_other_case_ids_pr__nf_c_1_9_1_other_case_ids'),
        ),
        migrations.AddConstraint(
            model_name='c_1_identification_case_safety_report',
            constraint=models.CheckConstraint(check=models.Q(('c_1_11_1_report_nullification_amendment__in', app.src.enums.C_1_11_1_report_nullification_amendment)), name='choics__c_1_11_1_report_nullification_amendment'),
        ),
        migrations.AddConstraint(
            model_name='c_1_9_1_r_source_case_id',
            constraint=models.UniqueConstraint(fields=('c_1_identification_case_safety_report', 'c_1_9_1_r_2_case_id'), name='unqtgr__c_1_identification_case_s__c_1_9_1_r_2_case_id'),
        ),
        migrations.AddConstraint(
            model_name='c_1_10_r_identification_number_report_linked',
            constraint=models.UniqueConstraint(fields=('c_1_identification_case_safety_report', 'c_1_10_r_identification_number_report_linked'), name='unqtgr__c_1_identification_case_s__c_1_10_r_identification_n'),
        ),
    ]
