# Generated by Django 5.0.2 on 2024-03-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_c_1_6_1_r_documents_held_by_sender_c_1_identification_of_the_case_safety_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_1_identification_case_safety_report',
            name='nf_c_1_7_fulfil_local_criteria_expedited_report',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='c_1_identification_case_safety_report',
            name='nf_c_1_9_1_other_case_ids_previous_transmissions',
            field=models.CharField(null=True),
        ),
    ]
