# Generated by Django 5.0.2 on 2024-03-16 21:34

import app.src.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_c_1_identification_case_safety_report_c_1_11_1_report_nullification_amendment_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='c_1_10_r_identification_number_report_linked',
            name='unqtgr__c_1_identification_case_s__c_1_10_r_identification_n',
        ),
        migrations.RemoveConstraint(
            model_name='c_1_9_1_r_source_case_id',
            name='unqtgr__c_1_identification_case_s__c_1_9_1_r_2_case_id',
        ),
        migrations.RemoveConstraint(
            model_name='c_1_identification_case_safety_report',
            name='choics__c_1_3_type_report',
        ),
        migrations.RemoveConstraint(
            model_name='c_1_identification_case_safety_report',
            name='choics__nf_c_1_7_fulfil_local_criteria_expedited_report',
        ),
        migrations.RemoveConstraint(
            model_name='c_1_identification_case_safety_report',
            name='anynul__c_1_7_fulfil_local_criter__nf_c_1_7_fulfil_local_cri',
        ),
        migrations.RemoveConstraint(
            model_name='c_1_identification_case_safety_report',
            name='choics__c_1_8_2_first_sender',
        ),
        migrations.RemoveConstraint(
            model_name='c_1_identification_case_safety_report',
            name='choics__c_1_9_1_other_case_ids_previous_transmissions',
        ),
        migrations.RemoveConstraint(
            model_name='c_1_identification_case_safety_report',
            name='choics__nf_c_1_9_1_other_case_ids_previous_transmissions',
        ),
        migrations.RemoveConstraint(
            model_name='c_1_identification_case_safety_report',
            name='anynul__c_1_9_1_other_case_ids_pr__nf_c_1_9_1_other_case_ids',
        ),
        migrations.RemoveConstraint(
            model_name='c_1_identification_case_safety_report',
            name='choics__c_1_11_1_report_nullification_amendment',
        ),
        migrations.AddConstraint(
            model_name='c_1_10_r_identification_number_report_linked',
            constraint=models.UniqueConstraint(fields=('c_1_identification_case_safety_report', 'c_1_10_r_identification_number_report_linked'), name='unqtgr__C_1_10_r_identif__c_1_identificati__c_1_10_r_identif'),
        ),
        migrations.AddConstraint(
            model_name='c_1_9_1_r_source_case_id',
            constraint=models.UniqueConstraint(fields=('c_1_identification_case_safety_report', 'c_1_9_1_r_2_case_id'), name='unqtgr__C_1_9_1_r_source__c_1_identificati__c_1_9_1_r_2_case'),
        ),
        migrations.AddConstraint(
            model_name='c_1_identification_case_safety_report',
            constraint=models.CheckConstraint(check=models.Q(('c_1_7_fulfil_local_criteria_expedited_report__isnull', True), ('nf_c_1_7_fulfil_local_criteria_expedited_report__isnull', True), _connector='OR'), name='anynul__C_1_identificati__c_1_7_fulfil_loc__nf_c_1_7_fulfil'),
        ),
        migrations.AddConstraint(
            model_name='c_1_identification_case_safety_report',
            constraint=models.CheckConstraint(check=models.Q(('c_1_9_1_other_case_ids_previous_transmissions__isnull', True), ('nf_c_1_9_1_other_case_ids_previous_transmissions__isnull', True), _connector='OR'), name='anynul__C_1_identificati__c_1_9_1_other_ca__nf_c_1_9_1_other'),
        ),
        migrations.AddConstraint(
            model_name='c_1_identification_case_safety_report',
            constraint=models.CheckConstraint(check=models.Q(('c_1_3_type_report__in', app.src.enums.C_1_3_type_report)), name='choics__C_1_identification_case_s__c_1_3_type_report'),
        ),
        migrations.AddConstraint(
            model_name='c_1_identification_case_safety_report',
            constraint=models.CheckConstraint(check=models.Q(('nf_c_1_7_fulfil_local_criteria_expedited_report__in', [app.src.enums.NullFlavor['NI']])), name='choics__C_1_identification_case_s__nf_c_1_7_fulfil_local_cri'),
        ),
        migrations.AddConstraint(
            model_name='c_1_identification_case_safety_report',
            constraint=models.CheckConstraint(check=models.Q(('c_1_8_2_first_sender__in', app.src.enums.C_1_8_2_first_sender)), name='choics__C_1_identification_case_s__c_1_8_2_first_sender'),
        ),
        migrations.AddConstraint(
            model_name='c_1_identification_case_safety_report',
            constraint=models.CheckConstraint(check=models.Q(('c_1_9_1_other_case_ids_previous_transmissions__in', [True])), name='choics__C_1_identification_case_s__c_1_9_1_other_case_ids_pr'),
        ),
        migrations.AddConstraint(
            model_name='c_1_identification_case_safety_report',
            constraint=models.CheckConstraint(check=models.Q(('nf_c_1_9_1_other_case_ids_previous_transmissions__in', [app.src.enums.NullFlavor['NI']])), name='choics__C_1_identification_case_s__nf_c_1_9_1_other_case_ids'),
        ),
        migrations.AddConstraint(
            model_name='c_1_identification_case_safety_report',
            constraint=models.CheckConstraint(check=models.Q(('c_1_11_1_report_nullification_amendment__in', app.src.enums.C_1_11_1_report_nullification_amendment)), name='choics__C_1_identification_case_s__c_1_11_1_report_nullifica'),
        ),
    ]
