# Generated by Django 5.0.2 on 2024-03-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_c_1_10_r_identification_number_report_linked_unqtgr__c_1_identification_case_s__c_1_10_r_iden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_1_identification_case_safety_report',
            name='c_1_2_date_creation',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='c_1_identification_case_safety_report',
            name='c_1_4_date_report_first_received_source',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='c_1_identification_case_safety_report',
            name='c_1_5_date_most_recent_information',
            field=models.CharField(null=True),
        ),
    ]
