# Generated by Django 5.0.2 on 2024-03-17 13:35

import app.src.enums
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_c_1_identification_case_safety_report_c_1_2_date_creation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='C_2_r_primary_source_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_2_r_1_1_reporter_title', models.CharField(max_length=50, null=True)),
                ('nf_c_2_r_1_1_reporter_title', models.CharField(choices=[(app.src.enums.NullFlavor['MSK'], app.src.enums.NullFlavor['MSK']), (app.src.enums.NullFlavor['ASKU'], app.src.enums.NullFlavor['ASKU']), (app.src.enums.NullFlavor['NASK'], app.src.enums.NullFlavor['NASK']), (app.src.enums.NullFlavor['UNK'], app.src.enums.NullFlavor['UNK'])], null=True)),
                ('c_2_r_1_2_reporter_given_name', models.CharField(max_length=60, null=True)),
                ('nf_c_2_r_1_2_reporter_given_name', models.CharField(choices=[(app.src.enums.NullFlavor['MSK'], app.src.enums.NullFlavor['MSK']), (app.src.enums.NullFlavor['ASKU'], app.src.enums.NullFlavor['ASKU']), (app.src.enums.NullFlavor['NASK'], app.src.enums.NullFlavor['NASK'])], null=True)),
                ('c_2_r_1_3_reporter_middle_name', models.CharField(max_length=60, null=True)),
                ('nf_c_2_r_1_3_reporter_middle_name', models.CharField(choices=[(app.src.enums.NullFlavor['MSK'], app.src.enums.NullFlavor['MSK']), (app.src.enums.NullFlavor['ASKU'], app.src.enums.NullFlavor['ASKU']), (app.src.enums.NullFlavor['NASK'], app.src.enums.NullFlavor['NASK'])], null=True)),
                ('c_2_r_1_4_reporter_family_name', models.CharField(max_length=60, null=True)),
                ('nf_c_2_r_1_4_reporter_family_name', models.CharField(choices=[(app.src.enums.NullFlavor['MSK'], app.src.enums.NullFlavor['MSK']), (app.src.enums.NullFlavor['ASKU'], app.src.enums.NullFlavor['ASKU']), (app.src.enums.NullFlavor['NASK'], app.src.enums.NullFlavor['NASK'])], null=True)),
                ('c_2_r_2_1_reporter_organisation', models.CharField(max_length=60, null=True)),
                ('nf_c_2_r_2_1_reporter_organisation', models.CharField(choices=[(app.src.enums.NullFlavor['MSK'], app.src.enums.NullFlavor['MSK']), (app.src.enums.NullFlavor['ASKU'], app.src.enums.NullFlavor['ASKU']), (app.src.enums.NullFlavor['NASK'], app.src.enums.NullFlavor['NASK'])], null=True)),
                ('c_2_r_2_2_reporter_department', models.CharField(max_length=60, null=True)),
                ('nf_c_2_r_2_2_reporter_department', models.CharField(choices=[(app.src.enums.NullFlavor['MSK'], app.src.enums.NullFlavor['MSK']), (app.src.enums.NullFlavor['ASKU'], app.src.enums.NullFlavor['ASKU']), (app.src.enums.NullFlavor['NASK'], app.src.enums.NullFlavor['NASK'])], null=True)),
                ('c_2_r_2_3_reporter_street', models.CharField(max_length=100, null=True)),
                ('nf_c_2_r_2_3_reporter_street', models.CharField(choices=[(app.src.enums.NullFlavor['MSK'], app.src.enums.NullFlavor['MSK']), (app.src.enums.NullFlavor['ASKU'], app.src.enums.NullFlavor['ASKU']), (app.src.enums.NullFlavor['NASK'], app.src.enums.NullFlavor['NASK'])], null=True)),
                ('c_2_r_2_4_reporter_city', models.CharField(max_length=35, null=True)),
                ('nf_c_2_r_2_4_reporter_city', models.CharField(choices=[(app.src.enums.NullFlavor['MSK'], app.src.enums.NullFlavor['MSK']), (app.src.enums.NullFlavor['ASKU'], app.src.enums.NullFlavor['ASKU']), (app.src.enums.NullFlavor['NASK'], app.src.enums.NullFlavor['NASK'])], null=True)),
                ('c_2_r_2_5_reporter_state_province', models.CharField(max_length=40, null=True)),
                ('nf_c_2_r_2_5_reporter_state_province', models.CharField(choices=[(app.src.enums.NullFlavor['MSK'], app.src.enums.NullFlavor['MSK']), (app.src.enums.NullFlavor['ASKU'], app.src.enums.NullFlavor['ASKU']), (app.src.enums.NullFlavor['NASK'], app.src.enums.NullFlavor['NASK'])], null=True)),
                ('c_2_r_2_6_reporter_postcode', models.CharField(max_length=15, null=True)),
                ('nf_c_2_r_2_6_reporter_postcode', models.CharField(choices=[(app.src.enums.NullFlavor['MSK'], app.src.enums.NullFlavor['MSK']), (app.src.enums.NullFlavor['ASKU'], app.src.enums.NullFlavor['ASKU']), (app.src.enums.NullFlavor['NASK'], app.src.enums.NullFlavor['NASK'])], null=True)),
                ('c_2_r_2_7_reporter_telephone', models.CharField(max_length=33, null=True)),
                ('nf_c_2_r_2_7_reporter_telephone', models.CharField(choices=[(app.src.enums.NullFlavor['MSK'], app.src.enums.NullFlavor['MSK']), (app.src.enums.NullFlavor['ASKU'], app.src.enums.NullFlavor['ASKU']), (app.src.enums.NullFlavor['NASK'], app.src.enums.NullFlavor['NASK'])], null=True)),
                ('c_2_r_3_reporter_country_code', models.CharField(max_length=2, null=True)),
                ('c_2_r_4_qualification', models.IntegerField(choices=[(app.src.enums.C_2_r_4_qualification['PHYSICIAN'], app.src.enums.C_2_r_4_qualification['PHYSICIAN']), (app.src.enums.C_2_r_4_qualification['PHARMACIST'], app.src.enums.C_2_r_4_qualification['PHARMACIST']), (app.src.enums.C_2_r_4_qualification['OTHER_HEALTH_PROFESSIONAL'], app.src.enums.C_2_r_4_qualification['OTHER_HEALTH_PROFESSIONAL']), (app.src.enums.C_2_r_4_qualification['LAWYER'], app.src.enums.C_2_r_4_qualification['LAWYER']), (app.src.enums.C_2_r_4_qualification['CONSUMER_OR_OTHER_NON_HEALTH_PROFESSIONAL'], app.src.enums.C_2_r_4_qualification['CONSUMER_OR_OTHER_NON_HEALTH_PROFESSIONAL'])], null=True)),
                ('nf_c_2_r_4_qualification', models.CharField(choices=[(app.src.enums.NullFlavor['UNK'], app.src.enums.NullFlavor['UNK'])], null=True)),
                ('c_2_r_5_primary_source_regulatory_purposes', models.IntegerField(choices=[(app.src.enums.C_2_r_5_primary_source_regulatory_purposes['PRIMARY'], app.src.enums.C_2_r_5_primary_source_regulatory_purposes['PRIMARY'])], null=True)),
                ('icsr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_2_r_primary_source_information', to='app.icsr')),
            ],
        ),
        migrations.CreateModel(
            name='C_3_information_sender_case_safety_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_3_1_sender_type', models.IntegerField(choices=[(app.src.enums.C_3_1_sender_type['PHARMACEUTICAL_COMPANY'], app.src.enums.C_3_1_sender_type['PHARMACEUTICAL_COMPANY']), (app.src.enums.C_3_1_sender_type['REGULATORY_AUTHORITY'], app.src.enums.C_3_1_sender_type['REGULATORY_AUTHORITY']), (app.src.enums.C_3_1_sender_type['HEALTH_PROFESSIONAL'], app.src.enums.C_3_1_sender_type['HEALTH_PROFESSIONAL']), (app.src.enums.C_3_1_sender_type['REGIONAL_PHARMACOVIGILANCE_CENTRE'], app.src.enums.C_3_1_sender_type['REGIONAL_PHARMACOVIGILANCE_CENTRE']), (app.src.enums.C_3_1_sender_type['WHO_COLLABORATING_CENTRES_FOR_INTERNATIONAL_DRUG_MONITORING'], app.src.enums.C_3_1_sender_type['WHO_COLLABORATING_CENTRES_FOR_INTERNATIONAL_DRUG_MONITORING']), (app.src.enums.C_3_1_sender_type['OTHER'], app.src.enums.C_3_1_sender_type['OTHER']), (app.src.enums.C_3_1_sender_type['PATIENT_OR_CONSUMER'], app.src.enums.C_3_1_sender_type['PATIENT_OR_CONSUMER'])], null=True)),
                ('c_3_2_sender_organisation', models.CharField(max_length=100, null=True)),
                ('c_3_3_1_sender_department', models.CharField(max_length=60, null=True)),
                ('c_3_3_2_sender_title', models.CharField(max_length=50, null=True)),
                ('c_3_3_3_sender_given_name', models.CharField(max_length=60, null=True)),
                ('c_3_3_4_sender_middle_name', models.CharField(max_length=60, null=True)),
                ('c_3_3_5_sender_family_name', models.CharField(max_length=60, null=True)),
                ('c_3_4_1_sender_street_address', models.CharField(max_length=100, null=True)),
                ('c_3_4_2_sender_city', models.CharField(max_length=35, null=True)),
                ('c_3_4_3_sender_state_province', models.CharField(max_length=40, null=True)),
                ('c_3_4_4_sender_postcode', models.CharField(max_length=15, null=True)),
                ('c_3_4_5_sender_country_code', models.CharField(max_length=2, null=True)),
                ('c_3_4_6_sender_telephone', models.CharField(max_length=33, null=True)),
                ('c_3_4_7_sender_fax', models.CharField(max_length=33, null=True)),
                ('c_3_4_8_sender_email', models.CharField(max_length=100, null=True)),
                ('icsr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='c_3_information_sender_case_safety_report', to='app.icsr')),
            ],
        ),
        migrations.CreateModel(
            name='C_4_r_literature_reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_4_r_1_literature_reference', models.CharField(max_length=500, null=True)),
                ('nf_c_4_r_1_literature_reference', models.CharField(choices=[(app.src.enums.NullFlavor['ASKU'], app.src.enums.NullFlavor['ASKU']), (app.src.enums.NullFlavor['NASK'], app.src.enums.NullFlavor['NASK'])], null=True)),
                ('icsr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_4_r_literature_reference', to='app.icsr')),
            ],
        ),
        migrations.CreateModel(
            name='C_5_study_identification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_5_2_study_name', models.CharField(max_length=2000, null=True)),
                ('nf_c_5_2_study_name', models.CharField(choices=[(app.src.enums.NullFlavor['ASKU'], app.src.enums.NullFlavor['ASKU']), (app.src.enums.NullFlavor['NASK'], app.src.enums.NullFlavor['NASK'])], null=True)),
                ('c_5_3_sponsor_study_number', models.CharField(max_length=50, null=True)),
                ('nf_c_5_3_sponsor_study_number', models.CharField(choices=[(app.src.enums.NullFlavor['ASKU'], app.src.enums.NullFlavor['ASKU']), (app.src.enums.NullFlavor['NASK'], app.src.enums.NullFlavor['NASK'])], null=True)),
                ('c_5_4_study_type_reaction', models.IntegerField(choices=[(app.src.enums.C_5_4_study_type_reaction['CLINICAL_TRIALS'], app.src.enums.C_5_4_study_type_reaction['CLINICAL_TRIALS']), (app.src.enums.C_5_4_study_type_reaction['INDIVIDUAL_PATIENT_USE'], app.src.enums.C_5_4_study_type_reaction['INDIVIDUAL_PATIENT_USE']), (app.src.enums.C_5_4_study_type_reaction['OTHER_STUDIES'], app.src.enums.C_5_4_study_type_reaction['OTHER_STUDIES'])], null=True)),
                ('icsr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='c_5_study_identification', to='app.icsr')),
            ],
        ),
        migrations.CreateModel(
            name='C_5_1_r_study_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_5_1_r_1_study_registration_number', models.CharField(max_length=50, null=True)),
                ('nf_c_5_1_r_1_study_registration_number', models.CharField(choices=[(app.src.enums.NullFlavor['ASKU'], app.src.enums.NullFlavor['ASKU']), (app.src.enums.NullFlavor['NASK'], app.src.enums.NullFlavor['NASK'])], null=True)),
                ('c_5_1_r_2_study_registration_country', models.CharField(max_length=2, null=True)),
                ('nf_c_5_1_r_2_study_registration_country', models.CharField(choices=[(app.src.enums.NullFlavor['ASKU'], app.src.enums.NullFlavor['ASKU']), (app.src.enums.NullFlavor['NASK'], app.src.enums.NullFlavor['NASK'])], null=True)),
                ('c_5_study_identification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_5_1_r_study_registration', to='app.c_5_study_identification')),
            ],
        ),
        migrations.AddConstraint(
            model_name='c_2_r_primary_source_information',
            constraint=models.UniqueConstraint(fields=('icsr', 'c_2_r_5_primary_source_regulatory_purposes'), name='unqtgr__C_2_r_primary_so__icsr__c_2_r_5_primary'),
        ),
        migrations.AddConstraint(
            model_name='c_2_r_primary_source_information',
            constraint=models.CheckConstraint(check=models.Q(('c_2_r_1_1_reporter_title__isnull', True), ('nf_c_2_r_1_1_reporter_title__isnull', True), _connector='OR'), name='anynul__C_2_r_primary_so__c_2_r_1_1_report__nf_c_2_r_1_1_rep'),
        ),
        migrations.AddConstraint(
            model_name='c_2_r_primary_source_information',
            constraint=models.CheckConstraint(check=models.Q(('c_2_r_1_2_reporter_given_name__isnull', True), ('nf_c_2_r_1_2_reporter_given_name__isnull', True), _connector='OR'), name='anynul__C_2_r_primary_so__c_2_r_1_2_report__nf_c_2_r_1_2_rep'),
        ),
        migrations.AddConstraint(
            model_name='c_2_r_primary_source_information',
            constraint=models.CheckConstraint(check=models.Q(('c_2_r_1_3_reporter_middle_name__isnull', True), ('nf_c_2_r_1_3_reporter_middle_name__isnull', True), _connector='OR'), name='anynul__C_2_r_primary_so__c_2_r_1_3_report__nf_c_2_r_1_3_rep'),
        ),
        migrations.AddConstraint(
            model_name='c_2_r_primary_source_information',
            constraint=models.CheckConstraint(check=models.Q(('c_2_r_1_4_reporter_family_name__isnull', True), ('nf_c_2_r_1_4_reporter_family_name__isnull', True), _connector='OR'), name='anynul__C_2_r_primary_so__c_2_r_1_4_report__nf_c_2_r_1_4_rep'),
        ),
        migrations.AddConstraint(
            model_name='c_2_r_primary_source_information',
            constraint=models.CheckConstraint(check=models.Q(('c_2_r_2_1_reporter_organisation__isnull', True), ('nf_c_2_r_2_1_reporter_organisation__isnull', True), _connector='OR'), name='anynul__C_2_r_primary_so__c_2_r_2_1_report__nf_c_2_r_2_1_rep'),
        ),
        migrations.AddConstraint(
            model_name='c_2_r_primary_source_information',
            constraint=models.CheckConstraint(check=models.Q(('c_2_r_2_2_reporter_department__isnull', True), ('nf_c_2_r_2_2_reporter_department__isnull', True), _connector='OR'), name='anynul__C_2_r_primary_so__c_2_r_2_2_report__nf_c_2_r_2_2_rep'),
        ),
        migrations.AddConstraint(
            model_name='c_2_r_primary_source_information',
            constraint=models.CheckConstraint(check=models.Q(('c_2_r_2_3_reporter_street__isnull', True), ('nf_c_2_r_2_3_reporter_street__isnull', True), _connector='OR'), name='anynul__C_2_r_primary_so__c_2_r_2_3_report__nf_c_2_r_2_3_rep'),
        ),
        migrations.AddConstraint(
            model_name='c_2_r_primary_source_information',
            constraint=models.CheckConstraint(check=models.Q(('c_2_r_2_4_reporter_city__isnull', True), ('nf_c_2_r_2_4_reporter_city__isnull', True), _connector='OR'), name='anynul__C_2_r_primary_so__c_2_r_2_4_report__nf_c_2_r_2_4_rep'),
        ),
        migrations.AddConstraint(
            model_name='c_2_r_primary_source_information',
            constraint=models.CheckConstraint(check=models.Q(('c_2_r_2_5_reporter_state_province__isnull', True), ('nf_c_2_r_2_5_reporter_state_province__isnull', True), _connector='OR'), name='anynul__C_2_r_primary_so__c_2_r_2_5_report__nf_c_2_r_2_5_rep'),
        ),
        migrations.AddConstraint(
            model_name='c_2_r_primary_source_information',
            constraint=models.CheckConstraint(check=models.Q(('c_2_r_2_6_reporter_postcode__isnull', True), ('nf_c_2_r_2_6_reporter_postcode__isnull', True), _connector='OR'), name='anynul__C_2_r_primary_so__c_2_r_2_6_report__nf_c_2_r_2_6_rep'),
        ),
        migrations.AddConstraint(
            model_name='c_2_r_primary_source_information',
            constraint=models.CheckConstraint(check=models.Q(('c_2_r_2_7_reporter_telephone__isnull', True), ('nf_c_2_r_2_7_reporter_telephone__isnull', True), _connector='OR'), name='anynul__C_2_r_primary_so__c_2_r_2_7_report__nf_c_2_r_2_7_rep'),
        ),
        migrations.AddConstraint(
            model_name='c_2_r_primary_source_information',
            constraint=models.CheckConstraint(check=models.Q(('c_2_r_4_qualification__isnull', True), ('nf_c_2_r_4_qualification__isnull', True), _connector='OR'), name='anynul__C_2_r_primary_so__c_2_r_4_qualific__nf_c_2_r_4_quali'),
        ),
        migrations.AddConstraint(
            model_name='c_2_r_primary_source_information',
            constraint=models.CheckConstraint(check=models.Q(('nf_c_2_r_1_1_reporter_title__in', [app.src.enums.NullFlavor['MSK'], app.src.enums.NullFlavor['ASKU'], app.src.enums.NullFlavor['NASK'], app.src.enums.NullFlavor['UNK']])), name='choics__C_2_r_primary_source_info__nf_c_2_r_1_1_reporter_tit'),
        ),
        migrations.AddConstraint(
            model_name='c_2_r_primary_source_information',
            constraint=models.CheckConstraint(check=models.Q(('nf_c_2_r_1_2_reporter_given_name__in', [app.src.enums.NullFlavor['MSK'], app.src.enums.NullFlavor['ASKU'], app.src.enums.NullFlavor['NASK']])), name='choics__C_2_r_primary_source_info__nf_c_2_r_1_2_reporter_giv'),
        ),
        migrations.AddConstraint(
            model_name='c_2_r_primary_source_information',
            constraint=models.CheckConstraint(check=models.Q(('nf_c_2_r_1_3_reporter_middle_name__in', [app.src.enums.NullFlavor['MSK'], app.src.enums.NullFlavor['ASKU'], app.src.enums.NullFlavor['NASK']])), name='choics__C_2_r_primary_source_info__nf_c_2_r_1_3_reporter_mid'),
        ),
        migrations.AddConstraint(
            model_name='c_2_r_primary_source_information',
            constraint=models.CheckConstraint(check=models.Q(('nf_c_2_r_1_4_reporter_family_name__in', [app.src.enums.NullFlavor['MSK'], app.src.enums.NullFlavor['ASKU'], app.src.enums.NullFlavor['NASK']])), name='choics__C_2_r_primary_source_info__nf_c_2_r_1_4_reporter_fam'),
        ),
        migrations.AddConstraint(
            model_name='c_2_r_primary_source_information',
            constraint=models.CheckConstraint(check=models.Q(('nf_c_2_r_2_1_reporter_organisation__in', [app.src.enums.NullFlavor['MSK'], app.src.enums.NullFlavor['ASKU'], app.src.enums.NullFlavor['NASK']])), name='choics__C_2_r_primary_source_info__nf_c_2_r_2_1_reporter_org'),
        ),
        migrations.AddConstraint(
            model_name='c_2_r_primary_source_information',
            constraint=models.CheckConstraint(check=models.Q(('nf_c_2_r_2_2_reporter_department__in', [app.src.enums.NullFlavor['MSK'], app.src.enums.NullFlavor['ASKU'], app.src.enums.NullFlavor['NASK']])), name='choics__C_2_r_primary_source_info__nf_c_2_r_2_2_reporter_dep'),
        ),
        migrations.AddConstraint(
            model_name='c_2_r_primary_source_information',
            constraint=models.CheckConstraint(check=models.Q(('nf_c_2_r_2_3_reporter_street__in', [app.src.enums.NullFlavor['MSK'], app.src.enums.NullFlavor['ASKU'], app.src.enums.NullFlavor['NASK']])), name='choics__C_2_r_primary_source_info__nf_c_2_r_2_3_reporter_str'),
        ),
        migrations.AddConstraint(
            model_name='c_2_r_primary_source_information',
            constraint=models.CheckConstraint(check=models.Q(('nf_c_2_r_2_4_reporter_city__in', [app.src.enums.NullFlavor['MSK'], app.src.enums.NullFlavor['ASKU'], app.src.enums.NullFlavor['NASK']])), name='choics__C_2_r_primary_source_info__nf_c_2_r_2_4_reporter_cit'),
        ),
        migrations.AddConstraint(
            model_name='c_2_r_primary_source_information',
            constraint=models.CheckConstraint(check=models.Q(('nf_c_2_r_2_5_reporter_state_province__in', [app.src.enums.NullFlavor['MSK'], app.src.enums.NullFlavor['ASKU'], app.src.enums.NullFlavor['NASK']])), name='choics__C_2_r_primary_source_info__nf_c_2_r_2_5_reporter_sta'),
        ),
        migrations.AddConstraint(
            model_name='c_2_r_primary_source_information',
            constraint=models.CheckConstraint(check=models.Q(('nf_c_2_r_2_6_reporter_postcode__in', [app.src.enums.NullFlavor['MSK'], app.src.enums.NullFlavor['ASKU'], app.src.enums.NullFlavor['NASK']])), name='choics__C_2_r_primary_source_info__nf_c_2_r_2_6_reporter_pos'),
        ),
        migrations.AddConstraint(
            model_name='c_2_r_primary_source_information',
            constraint=models.CheckConstraint(check=models.Q(('nf_c_2_r_2_7_reporter_telephone__in', [app.src.enums.NullFlavor['MSK'], app.src.enums.NullFlavor['ASKU'], app.src.enums.NullFlavor['NASK']])), name='choics__C_2_r_primary_source_info__nf_c_2_r_2_7_reporter_tel'),
        ),
        migrations.AddConstraint(
            model_name='c_2_r_primary_source_information',
            constraint=models.CheckConstraint(check=models.Q(('c_2_r_4_qualification__in', app.src.enums.C_2_r_4_qualification)), name='choics__C_2_r_primary_source_info__c_2_r_4_qualification'),
        ),
        migrations.AddConstraint(
            model_name='c_2_r_primary_source_information',
            constraint=models.CheckConstraint(check=models.Q(('nf_c_2_r_4_qualification__in', [app.src.enums.NullFlavor['UNK']])), name='choics__C_2_r_primary_source_info__nf_c_2_r_4_qualification'),
        ),
        migrations.AddConstraint(
            model_name='c_2_r_primary_source_information',
            constraint=models.CheckConstraint(check=models.Q(('c_2_r_5_primary_source_regulatory_purposes__in', app.src.enums.C_2_r_5_primary_source_regulatory_purposes)), name='choics__C_2_r_primary_source_info__c_2_r_5_primary_source_re'),
        ),
        migrations.AddConstraint(
            model_name='c_3_information_sender_case_safety_report',
            constraint=models.CheckConstraint(check=models.Q(('c_3_1_sender_type__in', app.src.enums.C_3_1_sender_type)), name='choics__C_3_information_sender_ca__c_3_1_sender_type'),
        ),
        migrations.AddConstraint(
            model_name='c_4_r_literature_reference',
            constraint=models.CheckConstraint(check=models.Q(('c_4_r_1_literature_reference__isnull', True), ('nf_c_4_r_1_literature_reference__isnull', True), _connector='OR'), name='anynul__C_4_r_literature__c_4_r_1_literatu__nf_c_4_r_1_liter'),
        ),
        migrations.AddConstraint(
            model_name='c_4_r_literature_reference',
            constraint=models.CheckConstraint(check=models.Q(('nf_c_4_r_1_literature_reference__in', [app.src.enums.NullFlavor['ASKU'], app.src.enums.NullFlavor['NASK']])), name='choics__C_4_r_literature_referenc__nf_c_4_r_1_literature_ref'),
        ),
        migrations.AddConstraint(
            model_name='c_5_study_identification',
            constraint=models.CheckConstraint(check=models.Q(('c_5_2_study_name__isnull', True), ('nf_c_5_2_study_name__isnull', True), _connector='OR'), name='anynul__C_5_study_identi__c_5_2_study_name__nf_c_5_2_study_n'),
        ),
        migrations.AddConstraint(
            model_name='c_5_study_identification',
            constraint=models.CheckConstraint(check=models.Q(('c_5_3_sponsor_study_number__isnull', True), ('nf_c_5_3_sponsor_study_number__isnull', True), _connector='OR'), name='anynul__C_5_study_identi__c_5_3_sponsor_st__nf_c_5_3_sponsor'),
        ),
        migrations.AddConstraint(
            model_name='c_5_study_identification',
            constraint=models.CheckConstraint(check=models.Q(('nf_c_5_2_study_name__in', [app.src.enums.NullFlavor['ASKU'], app.src.enums.NullFlavor['NASK']])), name='choics__C_5_study_identification__nf_c_5_2_study_name'),
        ),
        migrations.AddConstraint(
            model_name='c_5_study_identification',
            constraint=models.CheckConstraint(check=models.Q(('nf_c_5_3_sponsor_study_number__in', [app.src.enums.NullFlavor['ASKU'], app.src.enums.NullFlavor['NASK']])), name='choics__C_5_study_identification__nf_c_5_3_sponsor_study_nu'),
        ),
        migrations.AddConstraint(
            model_name='c_5_study_identification',
            constraint=models.CheckConstraint(check=models.Q(('c_5_4_study_type_reaction__in', app.src.enums.C_5_4_study_type_reaction)), name='choics__C_5_study_identification__c_5_4_study_type_reaction'),
        ),
        migrations.AddConstraint(
            model_name='c_5_1_r_study_registration',
            constraint=models.CheckConstraint(check=models.Q(('c_5_1_r_1_study_registration_number__isnull', True), ('nf_c_5_1_r_1_study_registration_number__isnull', True), _connector='OR'), name='anynul__C_5_1_r_study_re__c_5_1_r_1_study__nf_c_5_1_r_1_stu'),
        ),
        migrations.AddConstraint(
            model_name='c_5_1_r_study_registration',
            constraint=models.CheckConstraint(check=models.Q(('c_5_1_r_2_study_registration_country__isnull', True), ('nf_c_5_1_r_2_study_registration_country__isnull', True), _connector='OR'), name='anynul__C_5_1_r_study_re__c_5_1_r_2_study__nf_c_5_1_r_2_stu'),
        ),
        migrations.AddConstraint(
            model_name='c_5_1_r_study_registration',
            constraint=models.CheckConstraint(check=models.Q(('nf_c_5_1_r_1_study_registration_number__in', [app.src.enums.NullFlavor['ASKU'], app.src.enums.NullFlavor['NASK']])), name='choics__C_5_1_r_study_registratio__nf_c_5_1_r_1_study_regist'),
        ),
        migrations.AddConstraint(
            model_name='c_5_1_r_study_registration',
            constraint=models.CheckConstraint(check=models.Q(('nf_c_5_1_r_2_study_registration_country__in', [app.src.enums.NullFlavor['ASKU'], app.src.enums.NullFlavor['NASK']])), name='choics__C_5_1_r_study_registratio__nf_c_5_1_r_2_study_regist'),
        ),
    ]
