# Generated by Django 5.0.2 on 2024-03-19 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_c_1_10_r_identification_number_report_linked_c_1_10_r_identification_number_report_linked_and_'),
    ]

    operations = [
        migrations.RenameField(
            model_name='g_k_4_r_dosage_information',
            old_name='g_k_4_r_9_2a_pharmaceutical_dose_fom_termid_version',
            new_name='g_k_4_r_9_2a_pharmaceutical_dose_form_termid_version',
        ),
    ]
