# Generated by Django 5.0.2 on 2024-03-19 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_g_k_4_r_9_2a_pharmaceutical_dose_fom_termid_version_g_k_4_r_dosage_information_g_k_4_r_9_2a_p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='h_narrative_case_summary',
            name='icsr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='h_narrative_case_summary', to='app.icsr'),
        ),
    ]
