# Generated by Django 5.0.2 on 2024-04-21 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_c_1_identification_case_safety_report_anynul__c_1_identificati__c_1_7_fulfil_loc__nf_c_1_7_fu'),
    ]

    operations = [
        migrations.CreateModel(
            name='hlgt_pref_term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(help_text='8-digit code to identify the High Level Group Term')),
                ('name', models.CharField(help_text='Full name of the High Level Group Term', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='meddra_release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField()),
                ('language', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='hlt_pref_term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(help_text='8-digit code to identify the High Level Term')),
                ('name', models.CharField(help_text='Full name of the High Level Term', max_length=100)),
                ('hlgt_pref_terms', models.ManyToManyField(related_name='hlt_pref_terms', to='app.hlgt_pref_term')),
                ('meddra_release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hlt_pref_terms', to='app.meddra_release')),
            ],
            options={
                'unique_together': {('code', 'meddra_release')},
            },
        ),
        migrations.AddField(
            model_name='hlgt_pref_term',
            name='meddra_release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hlgt_pref_terms', to='app.meddra_release'),
        ),
        migrations.CreateModel(
            name='soc_term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(help_text='8-digit code to identify the System Organ Class')),
                ('name', models.CharField(help_text='Full name of the System Organ Class', max_length=100)),
                ('abbrev', models.CharField(help_text='System Organ Class abbreviation', max_length=5)),
                ('meddra_release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soc_terms', to='app.meddra_release')),
            ],
            options={
                'unique_together': {('code', 'meddra_release')},
            },
        ),
        migrations.CreateModel(
            name='pref_term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(help_text='8-digit code to identify the Preferred Term')),
                ('name', models.CharField(help_text='Full name of the Preferred Term', max_length=100)),
                ('null_field', models.CharField(blank=True, help_text='This field is null', max_length=1)),
                ('hlt_pref_terms', models.ManyToManyField(related_name='pref_terms', to='app.hlt_pref_term')),
                ('meddra_release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pref_terms', to='app.meddra_release')),
                ('soc_term', models.ForeignKey(help_text='The primary System Organ Class to which the Preferred Term is linked', on_delete=django.db.models.deletion.CASCADE, related_name='pref_terms', to='app.soc_term')),
            ],
            options={
                'unique_together': {('code', 'meddra_release')},
            },
        ),
        migrations.AddField(
            model_name='hlgt_pref_term',
            name='soc_terms',
            field=models.ManyToManyField(related_name='hlgt_pref_terms', to='app.soc_term'),
        ),
        migrations.CreateModel(
            name='low_level_term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(help_text='8-digit code to identify the Lowest Level Term')),
                ('name', models.CharField(help_text='Full name of the Lowest Level Term', max_length=100)),
                ('currency', models.CharField(blank=True, help_text='Indicates whether the Lowest Level Term is current or non-current', max_length=1)),
                ('meddra_release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='low_level_terms', to='app.meddra_release')),
                ('pref_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='low_level_terms', to='app.pref_term')),
            ],
            options={
                'unique_together': {('code', 'meddra_release')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='hlgt_pref_term',
            unique_together={('code', 'meddra_release')},
        ),
    ]
