# Generated by Django 5.0.2 on 2024-05-11 22:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_hlgt_pref_term_meddra_release_hlt_pref_term_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='ISO 3166-1 alpha-2 code for the country', max_length=2, validators=[django.core.validators.MinLengthValidator(2)])),
                ('name', models.CharField(help_text='short name of the country')),
                ('language', models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3)])),
            ],
            options={
                'unique_together': {('code', 'language')},
            },
        ),
        migrations.CreateModel(
            name='LanguageCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='ISO 639-2 alpha-3 code for the language', max_length=3, validators=[django.core.validators.MinLengthValidator(3)])),
                ('name', models.CharField(help_text='Name of the language')),
                ('language', models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3)])),
            ],
            options={
                'unique_together': {('code', 'language')},
            },
        ),
    ]
