# Generated by Django 5.0.2 on 2024-05-13 23:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_ucumcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='DosageFormCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField()),
                ('name', models.CharField()),
                ('language', models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3)])),
            ],
            options={
                'unique_together': {('code', 'language')},
            },
        ),
        migrations.CreateModel(
            name='RouteOfAdministrationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField()),
                ('name', models.CharField()),
                ('language', models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3)])),
            ],
            options={
                'unique_together': {('code', 'language')},
            },
        ),
    ]
