# Generated by Django 5.0.2 on 2024-05-16 23:04
from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_log'),
    ]

    operations = [
        UnaccentExtension()
    ]
