import typing as t


class SupportsServiceMethods[T](t.Protocol):
    def read(self, model_class: type[T], pk: int) -> T: ...

    def create(self, model: T) -> int: ...

    def update(self, model: T) -> None: ...

    def delete(self, model_class: type[T], pk: int) -> None: ...