import typing as t


class Service[T](t.Protocol):
    def list(self, model_class: type[T]) -> list[int]: ...

    def read(self, model_class: type[T], pk: int) -> T: ...

    def create(self, model: T) -> T: ...

    def update(self, model: T, pk: int) -> T: ...

    def delete(self, model_class: type[T], pk: int) -> None: ...


class ServiceWithBusinessValidation[T](Service[T], t.Protocol):
    def business_validate(self, model: T) -> T: ...